In [1]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [2]:
base = pd.read_csv('iris.csv')
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

In [3]:
print(classe_dummy[:5])  # Imprime as primeiras 5 linhas para verificar a codificação

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [4]:
def criar_rede():
    k.clear_session()
    classificador = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax')])
    classificador.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
    return classificador

In [5]:
classificador = KerasClassifier(model=criar_rede, epochs=250, batch_size=10)

In [6]:
resultados = cross_val_score(estimator=classificador, X=previsores, y=classe_dummy, cv=10, scoring='accuracy')
media = resultados.mean()
print(media)

desvio = resultados.std()
print(desvio)


Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.2944 - loss: 1.1135    
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - categorical_accuracy: 0.3582 - loss: 1.1071
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3614 - loss: 1.1046 
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.4462 - loss: 1.0980 
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3413 - loss: 1.0966 
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - categorical_accuracy: 0.3376 - loss: 1.0952
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3535 - loss: 1.0967 
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3604 - loss: 1.0982 
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3657 - loss: 1.0931 
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3531 - loss: 1.0960 
Epoch 11/250
