In [1]:
import pandas as pd
import tensorflow as tf #tensoflow
import sklearn
import scikeras

from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [2]:
base = pd.read_csv('iris.csv')
previsores = base.iloc[:, 0:4].values
classe = base.iloc[:, 4].values
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
classe_dummy = np_utils.to_categorical(classe)

In [3]:
print(classe_dummy[:5])  # Imprime as primeiras 5 linhas para verificar a codificação

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [4]:
def criar_rede():
    k.clear_session()
    classificador = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=4, activation='relu'),
    tf.keras.layers.Dense(units=3, activation='softmax')])
    classificador.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
    return classificador

In [5]:
classificador = KerasClassifier(model=criar_rede, epochs=250, batch_size=10)

In [6]:
resultados = cross_val_score(estimator=classificador, 
                             X=previsores, y=classe_dummy, 
                             cv=10, scoring='accuracy')
media = resultados.mean()
print(media)

desvio = resultados.std()
print(desvio)


Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.2785 - loss: 1.1350
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2188 - loss: 1.1471 
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.1915 - loss: 1.1374     
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2039 - loss: 1.0830 
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2714 - loss: 0.9936 
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2306 - loss: 0.9975 
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3420 - loss: 0.9423 
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.4381 - loss: 0.9331 
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.6261 - loss: 0.9071 
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.7473 - loss: 0.8828 
Epoch 11/250
14